g = TinkerGraph.open()
person1 = g.addVertex(Element.ID, 1, "name", "Scott", "age", 36)
person2 = g.addVertex(Element.ID, 2, "name", "Bob", "age", 47)
person3 = g.addVertex(Element.ID, 3, "name", "Anne", "age", 34)
person4 = g.addVertex(Element.ID, 4, "name", "Susan", "age", 45)
book1 = g.addVertex(Element.ID, 5, "title", "Solaris", "category", "novel")
book2 = g.addVertex(Element.ID, 6, "title", "Roadside Picnic", "category", "novel")
book3 = g.addVertex(Element.ID, 7, "title", "Annihilation", "category", "novel")
book4 = g.addVertex(Element.ID, 8, "title", "Brief History of Time", "category", "nonfiction")
person1.addEdge("read", book3, Element.ID, 9)
person1.addEdge("read", book3, Element.ID, 10)
person2.addEdge("read", book4, Element.ID, 11)
person2.addEdge("read", book2, Element.ID, 12)
person3.addEdge("read", book1, Element.ID, 13)
person4.addEdge("read", book1, Element.ID, 14)
person1.addEdge("friend", person2, Element.ID, 15)
person1.addEdge("friend", person3, Element.ID, 16)
person2.addEdge("friend", person3, Element.ID, 17)

scott=g.v(1)

